-- +goose Up
CREATE TABLE IF NOT EXISTS accounts
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS account_histories
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    old_balance BIGINT NOT NULL,
    new_balance BIGINT NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT account_histories_account_id_fk
        FOREIGN KEY (account_id)
        REFERENCES accounts (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS account_histories_account_id_idx
    ON account_histories (account_id);

-- +goose Down
DROP TABLE IF EXISTS account_histories;
DROP TABLE IF EXISTS accounts;